[package]
name = "infrastructure"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../shared" }
domain = { path = "../domain" }
sqlx = { workspace = true }
redis = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
async-trait = "0.1"
tokio = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
dotenvy = { workspace = true }